name: Publish 🔥

on: 
  workflow_dispatch:
  push: 
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: BPR2Test
  AZURE_CONTAINER_REGISTRY: bpr2testRegistry.azurecr.io
  DOCKER_IMAGE_NAME: bpr2test
  DOCKER_TAG: latest   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} -f ./BPR2Test/CI-CD-testv3/Dockerfile ./BPR2Test
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with: 
          app-name: "${{ env.AZURE_WEBAPP_NAME }}"
          publish-profile: '${{ secrets.AZURE_PUBLISH_PROFILE }}'
          images: "${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}"
